update notes + add 2 test types on CI and the cache on a daily basis

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -16,6 +16,10 @@ jobs:
         python-version: [ "pypy3.8", "3.8", "pypy3.9", "3.9", "3.10", "3.11" ]
 
     steps:
+      - name: Set date var
+        id: date
+        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
+
       - uses: actions/checkout@v3
 
       - name: Cache Data
@@ -23,7 +27,7 @@ jobs:
         uses: actions/cache@v3
         with:
           path: data
-          key: web-data
+          key: web-data-{{ steps.date.outputs.date }}
 
       - name: Fetch Data File Crime_Data_from_2020_to_Present.csv
         if: steps.cache-data.outputs.cache-hit != 'true'
@@ -49,9 +53,14 @@ jobs:
       - name: Install dependencies
         run: pip install .
 
-      # https://github.com/actions/setup-python/issues/350
       - name: Run tests
         run: python -m data_processing
+
+      # https://github.com/actions/setup-python/issues/350
+      - name: Run tests
+        run: pytest --benchmark-autosave --benchmark-save-data --benchmark-cprofile=tottime
+        # https://stackoverflow.com/questions/58858429/how-to-run-a-github-actions-step-even-if-the-previous-step-fails-while-still-f
+        if: success() || failure()
 
       - name: Archive performance coverage results
         uses: actions/upload-artifact@v3
